server:
  port: 8082

##
############ server 配置 (netty 参数) ##########

cqp:
  iot:
    server:
      serverName: test # 服务名
      port: 1884 # 端口
      protocol: CUSTOM # CUSTOM 自定义协议  MQTT  MQTT_WS_MQTT(mqtt.js)   MQTT_WS_PAHO(paho.js)
      bossThread: 1  #
      workThread: 2  #
      keepalive: true # Socket参数，连接保活，TCP会主动探测空闲连接的有效性。可以将此功能视为TCP的心跳机制
      reuseaddr: true # 地址复用  不需要等待 TIME_WAIT 后才能重用端口
      tcpNodelay: true # TCP参数，立即发送数据，默认值为Ture（Netty默认为True而操作系统默认为False）
      backlog: 1024  # TCP Socket参数，服务端接受连接的队列长度，如果队列已满，客户端连接将被拒绝
      sndbuf: 10485760 # Socket TCP数据发送缓冲区大小
      revbuf: 10485760 # Socket TCP数据接收缓冲区大小
      initalDelay: 10 # mqtt qos1 qos2 消息 重发延迟
      period: 10 # mqtt qos1 qos2 消息 重发周期
      heart: 180 # 系统心跳


############ server 配置 ##########



#logging:
#  level:
#    io.netty: debug
